### PR TITLE
Adding AtelierStoria parser

### PR DESCRIPTION
**Pull request by Oriol-GG**
Adds the parser for [atelierstoria.com](https://atelierstoria.com/).

Thanks to everyone in Discord, you guys were very helpful when I was setting the local environment, considering that I had never worked in .NET before it was quite more challenging than actually writing the parser which was pretty straightforward following your instructions in the readme.

I have tested everything according to the contribution guidelines, please let me know if I'm missing anything.

Thanks @aluhrs13 for making The Mini Index ❤️

### CODE REVIEW

**Review by anaximander23 — DISMISSED** [review]

**Comment by anaximander23** [comment]
Seems to work fine on my local version. Couple of minor style nitpicks (eg. method names should be CamelCase) but nothing that impacts functionality.

**Comment by Oriol-GG** [comment]
Thanks @anaximander23, I updated the method names. Let me know if there is anything else worth changing, thanks!

**Comment by aluhrs13** [comment]
I'll try to get this integrated this week, I just realized that continuous integration didn't work on my last change so I'm going to try to fix that, then pull this in. If I can't figure it out quickly enough I'll integrate this then manually deploy it.

**Comment by aluhrs13** [comment]
This has been merged and released, but I noticed a few links I tried weren't working. I opened #216 to track, it's probably an easy fix but I've been fighting deployment.

**Pull request merged**
